### ISSUE TITLE
The Preview Component isn't shown on Mobile Screen

### ISSUE THREAD

**Issue by jaydeepdey03** [elijahharry/searchpal#17]
<img width="527" alt="image" src="https://github.com/elijahharry/searchpal/assets/75583927/a50ee145-fd5e-415f-ac12-12298c8c1761">

**Comment by elijahharry** [comment]
@jaydeepdey03 Apologies for the late reply to this. The lack of option details on smaller screens was intentional, I felt like there wasn't enough space to show them.

If you're still using this library, I just released version 3.0.0. The API has completely changed and users now have complete control over what is rendered within the search palette.
